name: Upload 1GB File

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download file
        run: |
          curl -L -o file.bin "https://drive.usercontent.google.com/download?id=194vwHB6H8Qf2BE1ZyBdNrr335HImvFc0&export=download&confirm=t"

      - name: Verify file
        run: |
          ls -lh file.bin

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add file.bin .gitattributes || true
          git commit -m "upload large file"
          git push origin HEAD:${{ github.ref_name }}
